name: Moustache
version: 1.0
main: fr.zcraft.moustache.Moustache

api-version: 1.14
depend: 
  - SkinsRestorer

description: Moustaches !
authors:
  - Vlammar
  - Amaury Carrade

commands:
    moustache:
        description: Gestion des moustaches
